testenv: test
#appdriver: appium
#caps:
#  - chromedriverpath: '/Users/gaijinfeng/Downloads/chromedriver/2.37/chromedriver'
#    host: 127.0.0.1
#desiredcaps:
#  - platformName : 'android'
#    udid: 'emulator-5554'
#    deviceName: 'emulator-5554'
#    # Android
#    restart: true
#    package: com.dedao.juvenile
#    activity: com.dedao.juvenile.business.splash.SplashActivity
#    automationName: UiAutomator2
#    noReset: True
#    enableWebviewDetailsCollection: True
#    autoGrantPermissions: True
#    unicodeKeyboard: True
#    resetKeyboard: True
#    newCommandTimeout: 3600
#main:
#  - ${islogin} = isContain(免费专区)
web_driver: chrome
prefs:
  - profile.default_content_setting_values.media_stream_camera: 1
    profile.default_content_setting_values.media_stream_mic: 1
    profile.default_content_setting_values.notifications: 1
    profile.default_content_setting_values.geolocation: 1
path: '/data/chrome_driver/selenium/chromedriver'
url: 'https://live.igetcool.com/weblivev2/?roomId=2280703&scheduleId=493603544143499264'



testcase:
  #app登录
  - testcase/appTestcase/AppProfile.yaml
  #老师创建直播间
  - testcase/webTestcase/TeacherEntryRoom.yaml
  #学生进入教室
  - testcase/appTestcase/AppInClass.yaml
